### ISSUE TITLE
internal error when no arguments given

### ISSUE THREAD

**Issue by Ceddix** [CraftTogetherDE/SpectatorRotator#6]
Hi 👋🏼

There's a small issue with the `/spectate` command: If you try to use the command, without typing in any arguments, you get an internal error
![ingame-message](https://craft-together.de/~ceddix/uploads/javaw_y1g1fblnUw.png)
and following error is outputed in the console: https://pastebin.com/e4fTLrWm

You could add a message, that shows the right usage for the command, if no arguments are given.
(Shouldn't be hard to implement :p )

Thank you in advance, Ceddix!

**Comment by ghost** [comment]
Das ist ein Dev-Build.. der is noch gar nich released du Streber

**Comment by Ceddix** [comment]
So bug-reports aren't welcome? Bad developer...

**Comment by ghost** [comment]
🖕
